apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db
  namespace: test
  labels:
    name: postgres-db
    type: back-end
    app: user-service
data:
  POSTGRES_DB: user-service-db
  POSTGRES_USER: tester-app
  POSTGRES_PASSWORD: strong_password
